# Copy this file to nanoG_config.yaml and fill in local credentials.
APP_INFO:
  NAME: nanoG
  VERSION: 1.0
  AUTHOR: SJTU MIN LAB

websocket:
  port: 8004

graph_storage_cls: neo4j        # Select from [networkx, neo4j]

neo4j_settings:
  NEO4J_URL: neo4j://localhost:7687
  NEO4J_USER: neo4j
  NEO4J_PASSWORD: replace-me
  GENERATE_FROM_NETWORKX: True

use_conversation_func: openai   # Select from [openai, local]
use_embedding_func: openai      # Select from [openai, local]
llm_func_timeout: 300

openai_api_key: replace-me
openai_api_url: https://api.openai.com/v1

local_conversation_url: http://localhost:5678/v1/completions
local_embedding_url: http://localhost:5679/v1/embeddings
